name: github-pages

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.94.0'
      - name: Install node
        run: |
          sudo apt install nodejs
          node -v
      - name: Install postcss and autoprefixer
        run: npm i -g postcss-cli autoprefixer
      - name: Build site
        run: hugo --minify --cleanDestinationDir
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
