name: github-pages

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.wokrflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.93.2"

      - name: build
        run: hugo --minify

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
